medical_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.CreateArticleView.as_view(), name='create_article'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('list/', views.ArticleListView.as_view(), name='article_list'),

    path('<int:article_id>/comment/', views.article_comment, name='article_comment'),
    path('<int:article_id>/update/', views.UpdateArticleView.as_view(), name='update_article'),
    path('<int:article_id>/delete/', views.delete_article, name='delete_article'),

    path('topics/', views.TopicsListView.as_view(), name='topics_list'),
    path('topics/<str:topic_title>/', views.TopicsView.as_view(), name='topic'),
    path('topics/<str:topic_title>/subscribe/', views.topic_subscribe, name='topic_subscribe'),
    path('topics/<str:topic_title>/unsubscribe/', views.topic_unsubscribe, name='topic_unsubscribe'),

    path('users/', views.UserProfilesListView.as_view(), name='user_profiles_list'),
    path('preferred_articles/<int:user_id>/', views.preferred_articles, name='preferred_articles'),
    path('profile/<int:pk>/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('set-password/', views.SetPasswordView.as_view(), name='set_password'),
    path('set-userdata/', views.set_userdata),
    path('deactivate/', views.DeactivateProfileView.as_view(), name='deactivate_profile'),
    path('register/', views.RegisterProfileView.as_view(), name='register'),
    path('login/', views.LoginProfileView.as_view(), name='login'),
    path('logout/', views.LogoutProfileView.as_view(), name='logout'),

    re_path(r'archive\/\d{4}\/[01]?\d{1}\/', views.regex),

    path('<int:article_id>/', views.article_detail_view, name='article_detail_view'),
    path('add_comment/<int:article_id>/', views.add_comment, name='add_comment'),
]

medapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Topic(models.Model):
    title = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=255)
    users = models.ManyToManyField(UserModel, through='UserTopicRelationship')

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=255, default='default_title')
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    topics = models.ManyToManyField(Topic)

    def __str__(self):
        return self.title


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Comment by {self.author.username} on {self.article.title}"


class UserTopicRelationship(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    notify = models.BooleanField(default=False)

templates/article_list.html
{% extends "base.html" %}

{% block title %}Article List | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Article List</h2>
        <div class="row">
            {% for article in articles %}
                <div class="col-md-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h3 class="card-title">{{ article.title }}</h3>
                            <p class="card-text"><strong>Author:</strong> {{ article.author }}</p>
                            <p class="card-text"><strong>Created:</strong> {{ article.created_at|date:"F d, Y" }}</p>
                            <p class="card-text">{{ article.content }}</p>
                            <h4>Comments:</h4>
                            <ul>
                            {% for comment in article.comment_set.all %}
                                <li>{{ comment.author }}: {{ comment.message }}</li>
                            {% endfor %}
                            </ul>
                            <form method="post" action="{% url 'add_comment' article.id %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="message" >Add a Comment:</label>
                                    <textarea class="form-control" id="message" name="message" rows="3"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary btn-sm" style="background-color: #333; color: white; border-color: black">Add Comment</button>
                            </form>
                            {% if message %}
                                <p>{{ message }}</p>
                            {% endif %}
                            <a href="{% url 'update_article' article.id %}" class="btn btn-primary btn-sm" style="background-color: #333; color: white; border-color: black">Update</a>
                            <a href="{% url 'delete_article' article.id %}" class="btn btn-danger ml-2 btn-sm" style="background-color: #333; color: white; border-color: black" >Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/article_update.html
{% extends "base.html" %}


{% block title %}Update Article | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Update Article</h2>
        <form method="post">
            {% csrf_token %}
            <label for="title">Title:</label>
            <input type="text" name="title" value="{{ article.title }}" class="form-control mb-3">
            <label for="content">Content:</label>
            <textarea name="content" class="form-control mb-3">{{ article.content }}</textarea>
            <button type="submit" class="btn btn-primary" style="background-color: #333; color: white; border-color: black" >Update</button>
            <a href="{% url 'article_list' %}" class="btn btn-secondary ml-2" style="background-color: #333; color: white; border-color: black">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Medical Blog{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" 
    crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <style>
         
         body {
    background-image: url('https://ichef.bbci.co.uk/news/800/cpsprodpb/121BF/production/_104757147_gettyimages-962094932.jpg');
    background-size: cover;
    background-position: center;
    background-attachment: fixed;
    margin: 0;
    padding: 0;
    font-family: Arial, sans-serif;
}

header {
    background-color: rgba(0, 0, 0, 0.655);
    color: white;
    padding: 1rem 0;
    text-align: center;
}

nav {
    background-color: rgba(0, 0, 0, 0.5);
    padding: 10px 0;
    text-align: center; 
}

.nav-item {
    display: inline-block; 
    margin-right: 15px;
}

.nav-link {
    color: white;
    font-weight: bold;
    text-decoration: none;
    transition: color 0.3s, transform 0.3s;
    position: relative;
}

.nav-link:hover {
    color: #f8f9fa; 
    transform: scale(1.1); 
}

.nav-link::before {
    content: "";
    position: absolute;
    width: 100%;
    height: 2px;
    background-color: #f8f9fa;
    bottom: -4px;
    left: 0;
    transform: scaleX(0); 
    transform-origin: right;
    transition: transform 0.3s;
}

.nav-link:hover::before {
    transform: scaleX(1); 
    transform-origin: left;
}

main {
    padding: 2rem;
}

.content-block {
    background-color: rgba(255, 255, 255, 0.7);
    padding: 20px;
    margin: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
    backdrop-filter: blur(5px);
}

footer {
    text-align: center;
    padding: 1rem 0;
    background-color: rgba(0, 0, 0, 0.63);
    color: white;
}

.form-block {
    border: 1px solid #ccc;
    padding: 20px;
    border-radius: 10px;
    background-color: #f8f9fa;
    margin-bottom: 20px;
}

.form-group label {
    font-weight: bold;
}

.form-group input,
.form-group select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.form-group .text-danger {
    color: #dc3545;
}

.form-group .btn-primary {
    background-color: #007bff;
    border: none;
    padding: 10px 20px;
    color: #fff;
    border-radius: 5px;
}
    </style>
</head>
<body>
    <header>
        <figure class="text-center">
            <blockquote class="blockquote">
              <h1><p><em>Medical blog</em></p>
            </blockquote>
            <figcaption class="blockquote-footer">
              Share to us <cite title="useful information">useful information</cite>
            </figcaption>
          </figure>
            </h2>
        <nav>
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                {% if user.is_authenticated %}
                {% if user.is_staff %}  <!-- Check if the user is an admin -->
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">Admin Page</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/about/">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/list/">Articles list</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/logout/">Logout</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/create/">Create article</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/topics/">Topics</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/users/">User profile</a>
                </li>  
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/register/">Register</a>
                </li>

                <li class="nav-item">
                        <a class="nav-link" href="/login/">Login In</a>
                </li>    
                {% endif %}
                <!-- Add more navigation links here -->
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>&copy; 2023 Medical Blog</p>
    </footer>
</body>
</html>

templates/create_article.html
{% extends 'base.html' %}

{% block title %}Create Article | {{ block.super }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 form-block">
                <h2><em>Create Article</em></h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                        {% if form.title.errors %}
                            <small class="text-danger">{{ form.title.errors }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label_tag }}
                        {{ form.content }}
                        {% if form.content.errors %}
                            <small class="text-danger">{{ form.content.errors }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.topics.label_tag }}
                        {{ form.topics }}
                        {% if form.topics.errors %}
                            <small class="text-danger">{{ form.topics.errors }}</small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.author.label_tag }}
                        {{ form.author }}
                        {% if form.author.errors %}
                            <small class="text-danger">{{ form.author.errors }}</small>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary" style="background-color: #333; color: white; border-color: black;"><em>Create<em></em></button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/deactivate_profile.html
{% extends 'base.html' %}


{% block title %}Deactivate Profile | {{ block.super }}{% endblock %}

{% block content %}
    <section class="container mt-4 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Deactivate Your Profile</h2>
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to deactivate your profile?</p>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-danger">Deactivate Profile</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for article in all_articles %}
            <div class="col-md-4">
                <div class="content-block">
                    <h4><em>{{ article.title }}</em></h4>
                    <p><em>{{ article.content|truncatewords:30 }}</em></p>
                    <p><em><strong>Author:</strong> {{ article.author.username }}</em></p>
                    <a href="{% url 'article_detail_view' article_id=article.id %}" class="btn btn-primary" style="background-color: #333; color: white; border-color: black;"><em>Read More</em></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Login | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Login to Medical Blog</h3>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}"> 
                            <div class="mb-3">
                                {{ form.username }}
                                <label for="username" class="form-label">{{ form.username.label }}</label>
                                <!-- <input type="text" class="form-control" id="username" name="username" placeholder="Username"> -->
                                <div>{{ form.username.errors }}</div>
                            </div>
                            <div class="mb-3">
                                {{ form.password }}
                                <label for="password" class="form-label">{{ form.password.label }}</label>
                                <!-- <input type="password" class="form-control" id="password" name="password" placeholder="Username"> -->
                                <div>{{ form.password.errors }}</div>
                            </div>
                            <div>{{ form.errors }}</div>
                            <div class="d-grid gap-2">
                                <button class="w-100 btn btn-lg btn-outline-dark" type="submit">Log in</button>
                            </div>
                        </form>
                        <div class="my-3 text-center">
                            <p>Don't have an account?</p>
                            <a href="{% url 'register' %}" class="text-body fw-bold">Join us now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}


{% block title %}Register | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Join Medical Blog</h3>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                {{ form.username }}
                                <label for="username" class="form-label">Username</label>
                                <!-- <input type="text" class="form-control" id="username" name="username" required> -->
                                <label for='username'>{{  form.username.lable }}</label>
                                {% if form.username.errors %}
                                    <div class="text-danger">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                {{ form.email }}
                                <label for="email" class="form-label">{{ form.email.label }}</labe>
                                <div>{{ form.email.errors }}</div>
                                <!-- <input type="email" class="form-control" id="email" name="email" required> -->
                            </div>
                            <div class="mb-3">
                                {{ form.password }}
                                <label for="password1" class="form-label">{{ form.password.label }}</label>
                                <div>{{ form.password.errors }}</div>
                                <!-- <input type="password" class="form-control" id="password1" name="password1" required> -->
                            </div>
                            <div class="mb-3">
                                {{ form.confirm_password }}
                                <label for="password2" class="form-label">{{ form.confirm_password.label }}</label>
                                <div>{{ form.confirm_password.errors }}</div>
                                <!-- <input type="password" class="form-control" id="password2" name="password2" required> -->
                            </div>
                            <div class="d-grid gap-2">
                                <button class="w-100 btn btn-lg btn-outline-dark" type="submit">Register</button>
                            </div>
                        </form>
                        <div class="my-3 text-center">
                            <p>Already have an account?</p>
                            <a href="{% url 'login' %}" class="text-body fw-bold">Log in</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/set_password.html
{% extends 'base.html' %}

{% block title %}Set Password | {{ block.super }}{% endblock %}

{% block content %}
    <section class="container mt-4 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Set New Password</h2>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="new_password" class="form-label">New Password</label>
                                <input type="password" name="new_password" class="form-control" id="new_password" required>
                            </div>
                            <div class="mb-3">
                                <label for="confirm_password" class="form-label">Confirm Password</label>
                                <input type="password" name="confirm_password" class="form-control" id="confirm_password" required>
                            </div>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-primary">Change Password</button>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/topics.html
#Тут по тайтлу коли ми нажимаємо повинна відображатись інформація про статтю 
{% extends 'base.html' %}

{% block title %}Topics | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2>Topics</h2>
                <ul>
                    {% for topic in all_topics %}
                    <a href="{% url 'topic' topic_title=topic.title %}">{{ topic.title }}</a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/topics_list.html
{% extends 'base.html' %}

{% block title %}About | {{ block.super }}{% endblock %}

{% block content %}
    <section class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="text-center my-4"><em>Topics</em></h2>
                <ul class="list-group">
                    {% for topic in all_topics %}
                        <li class="list-group-item">
                            <a href="{% url 'topic' topic_title=topic.title %}" class="text-decoration-none">
                                <span class="bg-white bg-opacity-75 p-2 rounded">
                                    <em class="text-black">{{ topic.title }}</em>
                                </span>
                            </a>
                            {% if user.is_authenticated %}
                                {% if topic in user.subscriptions.all %}
                                <a href="{% url 'topic_unsubscribe' topic_title=topic.title %}" class="btn btn-danger btn-sm ml-2">Unsubscribe</a>
                                {% else %}
                                <a href="{% url 'topic_subscribe' topic_title=topic.title %}" class="btn btn-primary btn-sm ml-2">Subscribe</a>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

templates/unsubscribe.html
{% extends 'base.html' %}

{% block title %}Unsubscribe from {{ topic.title }} | Medical Blog{% endblock %}


{% block content %}
    <h2>Unsubscribe from {{ topic.title }}</h2>
    <p>You have successfully unsubscribed from {{ topic.title }} topic.</p>
{% endblock %}

templates/user_profile.html
{% extends 'base.html' %}


{% block title %}Edit User Profile | {{ block.super }}{% endblock %}

{% block content %}
    <section class="container mt-4 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Edit Your Profile</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" name="username" class="form-control" id="username" value="{{ user.username }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="first_name" class="form-label">First Name</label>
                                <input type="text" name="first_name" class="form-control" id="first_name" value="{{ user.first_name }}">
                            </div>
                            <div class="mb-3">
                                <label for="last_name" class="form-label">Last Name</label>
                                <input type="text" name="last_name" class="form-control" id="last_name" value="{{ user.last_name }}">
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" id="email" value="{{ user.email }}" required>
                            </div>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                                <a href="{% url 'deactivate_profile' %}" class="btn btn-danger">Deactivate Profile</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user_profiles_list.html
{% extends 'base.html' %}

{% block title %}User Profiles | {{ block.super }}{% endblock %}

{% block content %}
    <section class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="text-center my-4"><em>User Profiles</em></h2>
                <ul class="list-group">
                    {% for user in users %}
                        <li class="list-group-item">
                            <a href="{% url 'user_profile' user.pk user.username %}" class="text-decoration-none">
                                <span class="bg-white bg-opacity-75 p-2 rounded">
                                    <em class="text-black">{{ user.username }}</em>
                                </span>
                            </a>
                            <a href="{% url 'set_password' %}?user_id={{ user.id }}" class="btn btn-secondary btn-sm float-end">
                                Set Password
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
{% endblock %}